FROM node:18-alpine

WORKDIR /app

# Accept build arguments
ARG MONGODB_URI
ARG BETTER_AUTH_SECRET
ARG GEMINI_API_KEY
ARG NODEMAILER_PASSWORD

# Set them as environment variables
ENV MONGODB_URI=$MONGODB_URI
ENV BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET
ENV GEMINI_API_KEY=$GEMINI_API_KEY
ENV NODEMAILER_PASSWORD=$NODEMAILER_PASSWORD

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
